ft/CMakeLists.txt, ft/cachetable/cachetable.cc, ft/cachetable/cachetable.h, ft/cachetable/checkpoint.cc, ft/cachetable/checkpoint.h, ft/ft-flusher.cc, ft/ft-flusher.h, ft/ft-hot-flusher.cc, ft/ft-internal.h, ft/ft-ops.cc, ft/ft-status.cc, ft/ft-status.h, ft/logger/logger.cc, ft/logger/logger.h, ft/tests/cachetable-cleaner-thread-attrs-accumulate.cc, ft/tests/cachetable-simple-close.cc, ft/txn/txn.cc, ft/txn/txn.h, ft/ule.cc, ft/ule.h, locktree/locktree.h, locktree/manager.cc, locktree/tests/locktree_escalation_1big7lt_1small.cc, locktree/tests/locktree_escalation_2big_1lt.cc, locktree/tests/locktree_escalation_2big_2lt.cc, locktree/tests/locktree_escalation_impossible.cc, locktree/tests/locktree_escalation_stalls.cc, src/ydb.cc
Created new source files ft/ft-status.h and .cc to sort of "C++" the
way ft status values are handled. The problem is that each sub-system
handled stats slightly differently and usually used some static structs
local to only one.cc file. This made updating related stats across
files difficult, needing to add functions to expose stats to other
areas. Also made looking up stats a pain, needing to know were they
lived. Now, all stat enums for ft live in a single header and all stat
declarations are in a single .cc file and it is easy to manipulate/add
stats from anywhere.
=> FT-669 : Refactor status to it's own file/sybsystem within ft-index

ft/cachetable/checkpoint.cc, ft/ft-status.cc, ft/ft-status.h
Add new checkpoint status variables:
CP_END_TIME // checkpoint end time, time spend in checkpoint end operation in seconds
CP_LONG_END_COUNT // long checkpoint end count, count of end_checkpoint operations that exceeded 1 minute
CP_LONG_END_TIME // long checkpoint end time, total time of long checkpoints in seconds
=> FT-666 : Add more checkpoint status variables

ft/cachetable/cachetable-internal.h, ft/cachetable/cachetable.cc, ft/tests/test.h, src/tests/helgrind.suppressions
helgrind and drd complain when the evictor cond var is signaled with the associated mutex held.  this change grabs the evictor mutex when signaling the evictor.  an alternate design could suppress the error.  IMO, the code change is safer.
=> Unlocked signal evictor

ft/cachetable/cachetable-internal.h, ft/cachetable/cachetable.cc, ft/tests/test.h, ft/txn/txn.cc, src/tests/CMakeLists.txt, src/tests/helgrind.suppressions, src/ydb.cc
live txn iterator is allowed to read the state of txn that can be concurrently changed by the client thread that is using the txn.
2217: ==29744== Conflicting load by thread 36 at 0x1d69c8c0 size 8
2217: ==29744==    at 0x5082139: toku_txn_id64(__toku_db_txn*) (ydb_txn.cc:109)
2217: ==29744==    by 0x412202: iterate_txns(__toku_db_txn*, int (*)(__toku_db**, __toku_dbt*, __toku_dbt*, void*), void*, void*) (test_stress0.cc:146)
2217: ==29744==    by 0x50719E1: iter_txns_callback(tokutxn*, void*) (ydb.cc:2511)
2217: ==29744==    by 0x5133FC9: txn_manager_iter(txn_manager*, int (*)(tokutxn*, void*), void*, bool) (txn_manager.cc:916)
2217: ==29744==    by 0x5134072: toku_txn_manager_iter_over_live_root_txns(txn_manager*, int (*)(tokutxn*, void*), void*) (txn_manager.cc:954)
2217: ==29744== …
=> Iter txn race

ft/msg_buffer.cc, ft/msg_buffer.h, portability/memory.cc, portability/memory.h
From Bradley K. with some minor code format and logic touch-ups:
"In some situations, calls to malloc_usable_size() were taking significant CPU cycles.
(Vadim measured 8% on a workload with a fanout of 128.)
We can remember the usable size of the message buffers, saving those CPU cycles."
Took his original pull request, squashed into single commit, fixed very minor code formatting and return logic.
Jenkins: http://jenkins.percona.com/view/TokuDB/job/ft-index-param/27
=> FT-682 : don't call malloc_usable_size() so much

src/ydb.cc
Fixed compiler error when built under TokuDB and Percona Server by adding __attribute__((unused)).
=> FT-687 : FT-661 pull request #292 breaks Percona Server build

portability/toku_portability.h
Added simple FT_LIKELY and FT_UNLIKELY branch prediction macros similar to InnoDB UNIV_LIKELY and UNIV_UNLIKELY.
Functional only in GCC environments otherwise they are noops and simply evaluate the expression as if they didn't exist.
Macros not applied to any branches yet, just putting in place for use in ongoing work.
=> FT-685 : introduce branch prediction macros

ft/cachetable/cachetable.cc, ft/tests/cachetable-reserve-filenum.cc
[summary]
We have got an error on our production:
toku_cachetable_openfd_with_filenum: Assertion 'filenum.fileid != FILENUM_NONE.fileid' failed
From the gdb statck, I got:
(gdb) p reserved_filenum
= {fileid = 4294967295}
Deep in the 'reserve_filenum' codes, found that:
a) this function just return the m_next_filenum_to_use, not the un-used filenum.
b) m_next_filenum_to_use is UINT32， if we have many ft opens, it maybe overflow
From the crash instance data dir, we got one database has 180,000 tokudb files, so it's easy to trigger the assert.
Casey Brown has reported this issue here:
https://tokutek.atlassian.net/browse/DB-818
[testcase]
ft/tests/cachetable-reserve-filenum.cc
=> DB-818 fix reserved filenum overflow

ft/cachetable/cachetable.cc, ft/tests/cachetable-reserve-filenum.cc
[summary]
We have got an error on our production:
toku_cachetable_openfd_with_filenum: Assertion 'filenum.fileid != FILENUM_NONE.fileid' failed
From the gdb statck, I got:
(gdb) p reserved_filenum
= {fileid = 4294967295}
Deep in the 'reserve_filenum' codes, found that:
a) this function just return the m_next_filenum_to_use, not the un-used filenum.
b) m_next_filenum_to_use is UINT32， if we have many ft opens, it maybe overflow
From the crash instance data dir, we got one database has 180,000 tokudb files, so it's easy to trigger the assert.
Casey Brown has reported this issue here:
https://tokutek.atlassian.net/browse/FT-690
[test]
ft/tests/cachetable-reserve-filenum.cc
[reviewers]
prohaska7
Copyright (c) 2015, BohuTANG
Redistribution and use in source and binary …
=> FT-690 fix reserved filenum overflow

cmake_modules/TokuBuildTagDatabases.cmake
Swap option(USE_ETAGS ... ) and option(USE_CTAGS ... ) in
cmake_modules/TokuBuildTagDatabases.cmake, so that if USE_ETAGS is
processed first and USE_CTAGS then is properly disabled on Mac OS X.
=> FT-691 (CMake fails on case-insensitive FS, such as Mac OS X)

util/scoped_malloc.cc
Add missing stub functions toku_scoped_malloc_destroy_set and
toku_scoped_malloc_destroy_key for Mac OS X.
=> FT-694 (-DBUILD_TESTING=ON fails build on Mac OS X)

buildheader/make_tdb.cc
Add a dummy field to DB_LSN struct so its sizeof becomes the same in
both C and C++.
=> FT-692 (DB_LSN warning: empty struct has size 0 in C, size 1 in C++)

cmake_modules/TokuSetupCompiler.cmake
[+] new option for cmake (-DPROFILING)
[+] added -fno-omit-frame-pointer by request from Vadim and turned it on only if -DPROFILING is set
tested 3 times to make sure it works:
1) without -DPROFILING. result - -fno-omit-frame-pointer is not set
2) with -DPROFILING=on. result - -fno-omit-frame-pointer is set
3) with -DPROFILING=off. result - -fno-omit-frame-pointer is not set
=> added profiling option to allow profiling/debug. Jira ticket BLD-300

ft/ft-ops.cc, util/context.cc, util/context.h, util/tests/test-rwlock-cheapness.cc
found by address sanitizer when running the FT stress tests.
Copyright (c) 2015, Rich Prohaska
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribu
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
=> fix memory leak due to data race in context status initialization.

buildheader/make_tdb.cc, ft/cachetable/cachetable.cc, ft/cachetable/cachetable.h, src/ydb-internal.h, src/ydb.cc
Must be specified at ENV.open, not dynamic.
=> FT-678 : add thread pool size controls for CLIENT, CACHETABLE or CHECKPOINT

util/dmt.cc
remove extraneous null pointer checks since functions are annotated as nonnull.
Copyright (c) 2015, Rich Prohaska
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY …
=> compile with clang-3.8

ft/ft-status.cc
- Added pool names to string descriptions for engine status values.
=> FT-703 - 'pool_name' status missing actual pool name in engine status

buildheader/make_tdb.cc, src/ydb-internal.h, src/ydb.cc
If this option is not set the THP is not checked.
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/174/
http://jenkins.percona.com/job/percona-server-5.6-param/1135/
=> check_thp option is added

ft/serialize/compress.cc, portability/tests/test-max-data.cc, portability/toku_time.h, src/tests/recovery_fileops_unit.cc, third_party/xz-4.999.9beta/build-aux/config.guess
A set of fixes to make PerconaFT build and run on the AArch64 (64-bit ARMv8) architecture.
=> AArch64 portability fixes

ft/serialize/rbtree_mhs.cc, ft/tests/test-rbtree-insert-remove-without-mhs.cc
build FT with clang 3.9.0.  change node pair initializer.
fix memory leak in rbtree test found with clang 3.9.0 ASAN.
253:     #0 0x503910 in operator new(unsigned long) /home/rfp/projects/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78
253:     #1 0x507137 in test_insert_remove() /home/rfp/projects/tokuft.clang39/ft/tests/test-rbtree-insert-remove-without-mhs.cc:66:29
253:     #2 0x506ebf in test_main(int, char const**) /home/rfp/projects/tokuft.clang39/ft/tests/test-rbtree-insert-remove-without-mhs.cc:98:5
Copyright (c) 2016, Rich Prohaska
1. Redistributions of source code must retain the above copyright notice, this …
=> build FT with clang 3.9.0 and fix broken tests

cmake_modules/TokuSetupCompiler.cmake, ft/tests/ft-test.cc, ft/tests/pqueue-test.cc, src/tests/test_txn_abort5a.cc
fix OMT issues WRT non null parameters.  fix tests with misleading indentation that were identified with gcc 6.1.0.
Copyright (c) 2016, Rich Prohaska
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE …
=> compile with gcc 6.1.0

ft/ft-ops.cc, ft/ft-recount-rows.cc, ft/ft.cc, ft/node.cc, ft/node.h, ft/serialize/ft_node-serialize.cc, src/tests/stat64-root-changes.cc, tools/tokuftdump.cc
- Added mechanism to track adjustments made to logical row counts per node and undo those adjustments if the node is evicted without being persisted.
- Fixed counting of updates that get turned into insert messages.
- Fixed stat64 test that was incorrectly changed during initial logical row count testing.
- Formatting changes for each function touched.
=> FT-732 : logical row counts inaccurate

portability/memory.cc
- Fixed memory overwrite introduced in af3b8002786506fb3a042cefac14713d640f900d dir-per-db work in toku_strndup
=> lp1624993 : TokuDB heap corruption

src/ydb.cc
When some tokudb file is deleted and the file does not exist on the moment of
deletion don't treat it as error.
=> The fix for bug lp:1657908.

ft/ft-ops.cc, ft/node.cc, ft/node.h, ft/serialize/ft_node-serialize.cc
- Cleaned up access to BN logical_row_count_delta
- Moved lrc tracking back to individual basements and out of node itself due to
need to track at the basement level for partial eviction.
- Fixed missing handling of row adjustment on partial eviction.
- Corrected logic in flush_callback to only adjust when exactly appropriate
conditions.
- Corrected places to clear lrc adjustment counters when node gets written.
=> TDB-2 : row counts are being lost intermittently after restarts

ft/txn/roll.cc, src/tests/transactional_fileops.cc, src/ydb.cc
1) Once dir_per_db is enabled, env_dbrename exposes a bug of long
db/file name, which was hidden before.
2) The fix is very straightfoward. Simply return the system error
code to the upper level caller.
3) A ctest is modified to examine the patch path. No new ctest is
needed.
Jenkin link here: http://jenkins.percona.com/view/TokuDB/job/PerconaFT-param/77/
ubuntu-yakkety-64bit is failing for something irrelevant ... will investigate
=>  [TDB-6] src/ydb.cc:2917 can_acquire_table_lock: Assertion `r == 0'     failed (errno=36) (r=36)

CMakeLists.txt, buildheader/make_tdb.cc, ft/ft-ops.cc, ft/txn/txn.cc, ft/txn/txn.h, locktree/lock_request.cc, locktree/lock_request.h, locktree/locktree.h, locktree/manager.cc, locktree/tests/kill_waiter.cc, locktree/tests/lock_request_killed.cc, locktree/tests/lock_request_not_killed.cc, portability/toku_debug_sync.h, portability/toku_portability.h, src/tests/test_iterate_live_transactions.cc, src/tests/test_stress0.cc, src/ydb.cc, src/ydb_row_lock.cc, src/ydb_txn.cc, tools/CMakeLists.txt
TDB-27 : Add ability to kill query that is awaiting FT locktree lock
and
TDB-26 : Implement ability to use MySQL DEBUG_SYNC facility within PerconaFT
1) The ability to kill query blocked in lock-tree is added, see the initial pull request https://github.com/percona/PerconaFT/pull/360 .
2) The ability to use mysql debug_sync for mtr testing is added
See also:
https://github.com/percona/percona-server/pull/1738
https://github.com/percona/percona-server/pull/1739
MTR testing:
http://jenkins.percona.com/view/PS%205.6/job/percona-server-5.6-param/1896/
http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/934/
=> Kill query blocked in lock tree

buildheader/make_tdb.cc, ft/txn/txn.cc, ft/txn/txn.h, locktree/lock_request.cc, locktree/lock_request.h, locktree/locktree.cc, locktree/locktree.h, locktree/manager.cc, locktree/tests/kill_waiter.cc, locktree/tests/lock_request_killed.cc, locktree/tests/lock_request_not_killed.cc, locktree/tests/lock_request_start_release_wait.cc, locktree/tests/lock_request_start_retry_race_3.cc, locktree/tests/lock_request_start_retry_wait_race_2.cc, src/tests/test_iterate_live_transactions.cc, src/tests/test_stress0.cc, src/ydb.cc, src/ydb_txn.cc
1. Fix the release before wait race
The release before wait race occurs when a lock is released by transaction A after transaction B tried to acquire it but before transaction B has a chance to register it's pending lock request.  There are several ways to fix this problem, but we want to optimize for the common situation of minimal lock conflicts, which is what the lock acquisition algorithm currently does.  Our solution to the release before wait race is for transaction B to retry its lock request after its lock request has been added to the pending lock set.
1. Fix the retry race
The retry race occurs in the current lock retry algorithm which assumes that if some transaction is running lock retry, then my transaction does not also need to run it.  There is a chance that some pending …
=> fix bogus stalls in the lock tree for low concurrency applications

ft/cachetable/cachetable.cc, ft/cachetable/cachetable.h, ft/ft-ops.cc, ft/ft.cc, ft/node.h, ft/serialize/ft-serialize.cc, ft/serialize/ft-serialize.h, ft/serialize/ft_node-serialize.cc, ft/serialize/ft_node-serialize.h, tools/ftverify.cc, tools/tokuftdump.cc
TDB-23 : PerconaFT can assert when opening a dictionary with no useful information to error log
TDB-24 : PerconaFT asserts for various reasons deserializing nodes with no useful error output
=> TDB-23  TDB-24

portability/toku_debug_sync.h
Some macros are defined both in build options and mysql files, the fix is in
undefining such macros in the library code to avoid build errors.
Testing: http://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1079/
=> TDB-68: PerconaFT fails to build on debian wheezy 64 bit debug

buildheader/make_tdb.cc, src/tests/test_1672532.cc, src/ydb-internal.h, src/ydb_cursor.cc
Added a new flag DB_LOCKING_READ to fix TDB-9/bug-1672532
when lock in share mode was enabled the low(s) were not locked.
Basically it is a straightfoward patch that whenever to make a
decision if we should read-lock the row(s), do not only consider
the iso level but also the read locking flag. A ctest is added to
verify the patch.
There is also a minor change made in the ha_tokudb file, and two
small mtr tests added.
http://jenkins.percona.com/view/TokuDB/job/PerconaFT-param/89/
=> [TDB-9] TokuDB does not lock rows for writes with LOCK IN SHARE MODE

ft/ft-ops.cc, locktree/locktree.cc
The problem is that some tests are not linked to liblocktree, and must not be
linked logically, because the structure of the code assumes that some directory
in the code contains the code for the separate library, and the tests inside
such directory test the corresponding library. At the other hand liblocktree
contained the definition of some PFS keys which were used inside of locktree
code, but that keys are initialized in ft-ops.cc which is the part of libft
library. So when libft is used without liblocktree there are "undefined symbol"
errors.
The solution is to move that keys definition from locktree.cc to ft-ops.cc.
=> TDB-75: PerconaFT does not build standalone or with -DBUILD_TESTING=ON

ft/txn/rollback-apply.cc, src/tests/CMakeLists.txt, src/tests/rollback-inconsistency.cc
1. Essentially, we use the cachetable to keep the undo logs in the memory by saving the
undo entries into the rollback_log_nodes. When we have a large sequential inserts within
one txn, the rollback_log_node will grow and then spill out when it is beyond block_size
and there is a chance that undo log ends up being written to the disk upon checkpoint or
eviction.
The complication arises when a child txn commits and all of its undo logs gets merged
into that of its parent txn. This is done through swinging the log entry list from the
rollback_log_node of the child txn to that of the parent txn. But the impl had forgotten
to dirty the parent rollback_log_node...without any assertions, the bug is very hard to
manifest because the node is considered clean and gets evicted without flushing when …
=>  [FT-681] Transactional inconsistency with rollback

ft/loader/loader.cc, ft/serialize/ft-serialize.cc, util/dbt.cc
* Initialized some variables which were possibly uninitailized before
* Added fallthrough comments, or changed existing comments to the format gcc understands by default
=> lp1733637, BLD-861: Fixed compilation issues with gcc 7 and Werror

CMakeLists.txt, portability/toku_portability.h, portability/toku_pthread.h
TDB-93 : Unaligned pointers in perconaFT
* Ignoring a warning about unaligned pointers
* Changed the zero cond initializer: C++ doesn't need a zero, that's C
* Disabled deprecation warnings for stdc functions with Clang: it doesn't allow different function declarations
=> Fixing clang warnings/errors

src/tests/recovery_fileops_unit.cc
As the signed nature of char isn't specified in the C standard and we are using in a signed context here I'm making this explicit.
Compile error was:
src/tests/recovery_fileops_unit.cc:162:70: error: comparison is always true due to limited range of data type [-Werror=type-limits]
while ((c = getopt(argc, argv, "vqhcrO:A:B:C:D:E:F:G:H:I:J:X:")) != -1) {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
cc1plus: all warnings being treated as errors
$CXX --version (Power 8 Architecture)
g++ (GCC) 6.3.1 20170515
=> tests: compile error on arches where char is unsigned

portability/toku_time.h
One of the big gaps in Power enabled for tokudb was this function being missing.
=> Add POWER implementation for toku_time_now

ft/txn/rollback-apply.cc
Fix a data race in the rollback log found when running hotindexer-bw test with the thread sanitizer.  The problem was caused when a indexer thread and a client thread were simultaneously updating the same transaction rollback log.  There was a case where the rollback log was not locked with the transaction lock, which caused the data race to be discovered.
This fix is one of several that I discussed with George Lorch.
Copyright (c) 2018, Rik Prohaska
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above …
=> Fix a data race on the transaction rollback log found by the thread sanitizer

util/minicron.cc, util/tests/minicron-change-period-data-race.cc
A data race in the minicron between the 'do' and 'change period' functions was detected by the thread sanitizer.  The fix is trivial:  read the period while holding the minicron lock.  This pull request also includes a simple test case that exposes the data race when the code is compiled with the thread sanitizer.
Copyright (c) 2018, Rik Prohaska
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other …
=> Test and fix a minicron data race detected with the thread sanitizer.

ft/tests/test-TDB2-pe.cc, ft/tests/test-TDB89.cc
Two new tests with memory leaks cause valgrind failures.  Fix the TDB-2 and TDB-89 tests.
Copyright (c) 2018, Rik Prohaska
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF …
=> Fix memory leaks in TDB-2 and TDB-89 tests

portability/memory.h, util/dmt.cc
Fix the following warnings:
- type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
- unnecessary parentheses in declaration of ‘eresult’ [-Werror=parentheses]
=> PS-3950: gcc-8 compilation warnings

ft/tests/cachetable-simple-pin-nonblocking-cheap.cc
The cachetable-simple-pin-noblocking-cheap test occasionally fails due to a TOKUDB_TRY_AGAIN error being kicked out of the cachetable to the test.  The test does not expect this error so it crashes.  The TOKUDB_TRY_AGAIN error was caused by a locking conflict between the test and the cachetable evictor which periodically runs on a background thread.  Since the evictor is not an important part of this test, its execution was removed by setting the cachetable size larger than the test's cachetable footprint.
Tools:
Ubuntu 18.04
gcc 7.3.0
Cmake 3.10.2
Copyright (c) 2018, Rik Prohaska
Redistributions of source code must retain the …
=> the cachetable-simple-pin-nonblocking-cheap test occasionally fails due to a locking conflict with the cachetable evictor.

src/ydb.cc
shutdown_performance_schema() is always invoked before exit(), what means
global mutexes are always destroyed after perfomance schema shutdown, what
causes SIGFAULT on some platforms(debian wheeze in particular).
For PerconaFT layer the fix is in invoking ydb-layer deinitialization function
explicitly from storage engine shutdown function. But the same function is also
invoked on library unload, see libtokuft_destroy(). The certain flag is used to
avoid invoking ydb-layer deinitialization function twice.
Testing: 
https://jenkins.percona.com/view/5.7/job/mysql-5.7-param/1891/
See also: https://github.com/percona/percona-server/pull/2479
=> PS-4711: crash on TokuDB PFS-instrumented mutexes deinitialization

COPYING.APACHEv2, README.md, locktree/concurrent_tree.cc, locktree/concurrent_tree.h, locktree/keyrange.cc, locktree/keyrange.h, locktree/lock_request.cc, locktree/lock_request.h, locktree/locktree.cc, locktree/locktree.h, locktree/manager.cc, locktree/range_buffer.cc, locktree/range_buffer.h, locktree/treenode.cc, locktree/treenode.h, locktree/txnid_set.cc, locktree/txnid_set.h, locktree/wfg.cc, locktree/wfg.h, util/growable_array.h, util/omt.cc, util/omt.h
- Added new license text and files to allow the locktree to be used under
Apache version 2
=> PS-4849 : Re-license PerconaFT 'locktree' to Apache V2

ft/ft-ops.cc, portability/memory.cc, portability/portability.cc
- jemalloc mallctl_f("opt.lg_chunk", ...) is failing in memory init with
jemalloc 5.1.0.  This option was removed in 5.0.0 and versions of jemalloc
greater than 5.0 no longer operate with the concept of lg_chunk.  There is no
equivalent replacement functionality.  For this specific issue, lg_chunk is
used by PerconaFT to set the threshold where allocations will switch to using
mmap instead of the standard allocator.  It is reasonable to recognize the
lg_chunk query failure and pick a rational value and continue on rather than
failing and asserting.  For the older jemalloc versions, this value was 4MB
by default.
- Fixed missing initialization of global flag indicating memory startup status.
- Added more assertions in the startup path to catch specific issues.
- Altered behavior of …
=> PS-5406 - jemalloc 5.0.x causes TokuDB/PerconaFT to assert on load

cmake_modules/TokuMergeLibs.cmake
"-lpthread" is passed as a dependency to to library merge functions,
causing a CMake error because of a non existent target. This patch
excludes any external library starting with "-l" from these checks.
=> PS-5102: Fix configuration error with MySQL 8.0.16

cmake_modules/TokuThirdParty.cmake, portability/CMakeLists.txt, scripts/run-nightly-coverage-tests.bash, scripts/run-nightly-drd-tests.bash, scripts/run-nightly-release-tests.bash
Current cmake and build scripts refer to a "build_jemalloc" target,
which was never actually present in the git tree. Starting with
8.0.16, MySQL CMake scripts set CMP00046 to NEW, which emits errors
on non existing dependencies: the scripts work as before, and omit
a working makefile, but cmake reports an exit code of 1 in the end,
causing jenkins failures.
This change removes every mention of the build_jemalloc target,
fixing the issue.
=> PS-5102: Remove old build_jemalloc target

portability/toku_instr_mysql.cc
- MySQL Commit e4148f2a22922687f7652c4e3d21a22da07c9e78 alters PSI rwlock
interface, bumps version and deprecates prior interface.  This breaks
PerconaFT portability layer.  Must add #ifdef on
PSI_CURRENT_RWLOCK_VERSION to compile to appropriate interface for
unlock_rwlock.
=> PS-5363 : Merge MySQL 8.0.17

ft/ft-ops.cc, ft/ft-ops.h, ft/ft.h, src/ydb.cc, src/ydb_db.cc, src/ydb_db.h
This could be useful when the server crashed with a corrupted rollback file,
and is unable to start up. Specifying --tokudb--force-recovery=6 --super-read-only
should start it up in a read-only, but usable state. Some data may be lost and
unrecoverable.
Starting the server without the read only option is *NOT* supported.
=> PS-5932: Implementing --tokudb-force-recovery=6 to skip reading the logs

ft/ft-ops.cc
The FT layer is initialized in toku_ft_layer_init, which is
normally called in ydb_lib.cc as part of the DLL initialization
process.
For some reason, the linker previously optimized these construction
functions out in tools, and manual initialization calls were added.
In the original PS-5932 pull request, a global variable was added
to ydb.cc, which changed the linker beheavior: it no longer
optimized out the dll initialization function. This resulted in
double initialization in tools, asserting in debug builds.
Fix: as tokudb uses C++11 on all platforms, a static bool variable
is added as a guards around toku_ft_layer_init and _destroy:
the functions can be safely called multiple times now.
=> PS-5932: Fix double initialization in ft tools

portability/portability.cc
#warning directive was added to sys/sysctl.h in glibc>=2.30.
It is enough to disable it for PerconaFT/portability.
third_party/xz references above header as well, but in unused xz (not compiled) part (we compile only liblzma)
=> PS-5674: Fixed compilation error caused by #warning in sys/sysctrl.h

portability/memory.cc
The ASAN doesn't support mallopt, it simply returns 0 or -1
depending on GCC version. With GCC 10 it returns 0 and this leads
to assertion failure.
=> PS-7332: Skip mallopt in case code is built with ASAN support

CMakeLists.txt
MySql changed the way of adding the flag `-DENABLED_DEBUG_SYNC`,
which caused the variable not being recognized in CMakeLists.
https://github.com/mysql/mysql-server/blob/a9b0c712de3509d8d08d3ba385d41a4df6348775/CMakeLists.txt#L475
The proposed change is back compatible with the previous code.
=> PS-7621 - Improve detection of -DENABLED_DEBUG_SYNC in CMakeLists

.travis.yml
https://jira.percona.com/browse/PS-7704
Do not try to install `clang++` which matches a regex.
This is a copy of similar fix for PS from
https://github.com/percona/percona-server/commit/952e65845d1813b221ca9713a2c0b2ba805b67e7.
=> PS-7704: Travis CI: fix installation of clang-9 on Ubuntu Bionic

cmake_modules/TokuThirdParty.cmake
https://jira.percona.com/browse/PS-7622
=> PS-7622: Suppress implicit-fallthrough and unused-but-set-variable warn from liblzma

cmake_modules/TokuSetupCompiler.cmake
https://jira.percona.com/browse/PS-7622
At the moment there is a lot of "command-line option is valid for C/ObjC
but not for C++" warnings in build log. They all issued by check_c_compiler_flag
check in prepend_cflags_if_supported cmake macro.
Use check_cxx_source_compiles instead to check if flag is supported.
This allows to suppress all those warnings.
=> PS-7622: Improve prepend_cflags_if_supported cmake macro

cmake_modules/TokuFeatureDetection.cmake
https://jira.percona.com/browse/PS-7622
Fix "implicitly converting 'INTEGER' to 'STRING' type" warn while
setting CMAKE_TOKUDB_REVISION.
=> PS-7622: Fix cmake warn while setting CMAKE_TOKUDB_REVISION variable

cmake/merge_archives_unix.cmake.in
https://jira.percona.com/browse/PS-7811
Build fails with linker error "llvm-ar-5.0: Unknown command line
argument '-t'". Issue reproduced with clang-5.0 and cmake-3.21.
Removed "-" prefix before option to fix the issue.
=> PS-7811: Fix llvm-ar options in merge_archives_unix

portability/memory.cc, portability/memory.h
https://jira.percona.com/browse/PS-7947
The ASAN doesn't support mallopt. Avoid using it in case of build
with Clang ASAN.
=> PS-7947: Fix assertion in toku_memory_startup() with Clang ASAN

cmake_modules/TokuFeatureDetection.cmake, portability/toku_config.h.in, portability/toku_pthread.cc
https://jira.percona.com/browse/PS-8014
On Ubuntu 21.10 Impish both 'pthread_yield()' and 'pthread_yield_np()'
functions are considered deprecated and trigger warnings when they
are used. This does not allow 'check_function_exists()' CMake macro
detect if these functions are present in the system.
To fix this, we now also check for the 'sched_yield()' function
and fall back to it if the previous two are not found or considered
deprecated.
=> PS-8014 fix: Cannot find pthread_yield or pthread_yield_np when compiling PerconaFT on Impish

CMakeLists.txt
Newer CMake binaries started to generate a warning if 'cmake_minimum_required' 'VERSION' is less than '2.8.12'.
Increased this 'VERSION' to suppress the warning.
=> Changed cmake_minimum_required VERSION to 2.8.12
